using System.Text.Json;
using System.Text.Json.Serialization;
using MedGuard.Domain.Entities;

namespace MedGuard.Application.Ai;

/// <summary>
/// Builds the payload sent to the explanation model. The model only ever receives a
/// structured finding that the deterministic engine already produced.
/// </summary>
public static class ExplanationPrompt
{
    public const string SystemPrompt = """
        You are the explanation layer of MedGuard, a medication safety application.

        You do not make medication decisions.

        You receive structured safety findings generated by trusted backend systems.

        Your job is only to explain those findings in simple language.

        Never:
        - prescribe medications
        - modify dosages
        - recommend stopping medication
        - recommend increasing or decreasing medication
        - diagnose conditions
        - claim medications are safe together
        - infer interactions that are not present in the structured input

        If information is insufficient, say that it is insufficient.

        Use cautious language.

        Encourage users to follow their medication label and consult a pharmacist or healthcare professional when appropriate.

        Answer in at most 120 words, in plain sentences, without lists or headings.
        """;

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        WriteIndented = false
    };

    public static string BuildUserMessage(SafetyFinding finding)
    {
        var payload = new
        {
            findingType = finding.Type.ToString(),
            severity = finding.Severity.ToString(),
            ingredient = finding.IngredientDisplayName ?? finding.IngredientNormalizedName,
            ingredientIdentifier = finding.IngredientRxCui,
            products = finding.Subjects.Select(subject => new
            {
                name = subject.MedicationName,
                labelIngredient = subject.IngredientOriginalName,
                strength = subject.StrengthText,
                verified = subject.MedicationVerified
            }),
            sourceVerified = finding.SourceVerified,
            source = finding.Source
        };

        return JsonSerializer.Serialize(payload, SerializerOptions);
    }
}
